services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: trino-datasource
      GF_LOG_FILTERS: plugin.trino-datasource:debug
    depends_on:
      trino:
        condition: service_healthy

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "trino", "--execute", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
